### ISSUE TITLE
Caldroid Calendar bug

### ISSUE THREAD

**Issue by Jen030** [ucsdCSE110wi16/CSE110W260T13#11]
Caldroid Calendar shows up with a scrollable version of Android's native calendar in the background.
This is happening up to API 22.

Screenshot: http://i.imgur.com/KyoZdWy.png

**Comment by nick11roberts** [comment]
I'm on API 23 so I didn't catch it... My bad!

**Comment by nick11roberts** [comment]
I believe I fixed it, but I'm waiting because I'm installing the system image for x86 API 21... Taking forever... 

My fix includes using 'android.support.v4.app.FragmentTransaction' instead of 'FragmentTransaction.' Really sorry about that, that was a rookie mistake on my part... 

EDIT: did not fix it. 
EDIT: fixed a different way. See closing commit. 
EDIT: I left the support FragmentTransaction thing in there anyway because I think it has more broad support.

**Comment by nick11roberts** [comment]
Also I think that this means I'll have to up the min SDK version to 16...
