### ISSUE TITLE
Refactor databases

### ISSUE THREAD

**Issue by nick11roberts** [ucsdCSE110wi16/CSE110W260T13#16]
By the advice of one is the TAs, I am convinced that we should refactor our databases so that we have only one database with multiple tables. Also I don't think we actually need content providers. I believe that with this we can drastically simplify our codebase and increase productivity. I will do research as to how to do this.

**Comment by Jen030** [comment]
The purpose of the ContentProviders generally is to send information to other applications and back (which doesn't align with our app).

However, our application does user the Loader interface in order to update events immediately on change. I could not find a way to implement Loaders without ContentProviders so I ended up creating one.

If you could find a way to generalize the files in there, it'd be great. :+1:

**Comment by nick11roberts** [comment]
Awesome! Lol, my phone autocorrected refactor to retractor...

**Comment by nick11roberts** [comment]
I'll try to research it.

**Comment by Jen030** [comment]
Not enough time. Too few benefits in contrast to work needed to be done.

**Comment by nick11roberts** [comment]
Sounds good.
